"use client";

import React from "react";
import { Instrument_Serif } from "next/font/google";
import {
  DollarSign,
  Zap,
  Gift,
  ShieldCheck,
  Target,
  Trophy,
  Shield,
  Check,
  PartyPopper,
} from "lucide-react";

const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: ["400"],
});

const features = [
  {
    name: "1. Deposit LINK & Get Tickets",
    description:
      "You deposit Chainlink (LINK) tokens into the NoLo prize pool. For every amount equivalent to the ticket price, you get a ticket for the lottery. Your deposit is never spent and can be withdrawn at any time.",
    icon: DollarSign,
  },
  {
    name: "2. Generate Yield with Aave",
    description:
      "All the LINK in the pool is put to work on the Aave lending protocol, one of DeFi's most trusted platforms. This generates a safe and variable yield which forms the prize.",
    icon: Zap,
  },
  {
    name: "3. Automated & Fair Draws with Chainlink",
    description:
      "Chainlink Automation reliably triggers the prize draw at the end of each round. Then, Chainlink VRF (Verifiable Random Function) provides a provably random number to pick a winner, ensuring the process is fair and transparent.",
    icon: Gift,
  },
  {
    name: "4. Win the Prize or Keep Your Stake",
    description:
      "One lucky winner receives all the yield generated by the pool for that round. If you don't win, your original LINK deposit is untouched and automatically entered into the next round. You never lose your principal!",
    icon: ShieldCheck,
  },
];

const About = () => {
  return (
    <section id="about" className="bg-white py-24 sm:py-32">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="mx-auto max-w-2xl lg:text-center">
          <h2
            className={`text-base font-semibold leading-7 text-black/80 ${instrumentSerif.className}`}
          >
            How It Works
          </h2>
          <p
            className={`mt-2 text-4xl font-bold tracking-tight text-black sm:text-6xl ${instrumentSerif.className}`}
          >
            A Lottery Where You Can't Lose
          </p>
          <p className="mt-6 text-lg leading-8 text-black/60">
            NoLo is a revolutionary prize savings protocol. Deposit your LINK,
            get a chance to win the aggregated yield prize, and keep your
            initial deposit forever. Here's the step-by-step process.
          </p>
        </div>
        <div className="mx-auto mt-16 max-w-2xl sm:mt-20 lg:mt-24 lg:max-w-4xl">
          <dl className="grid max-w-xl grid-cols-1 gap-x-8 gap-y-10 lg:max-w-none lg:grid-cols-2 lg:gap-y-16">
            {features.map((feature) => (
              <div key={feature.name} className="relative pl-16">
                <dt className="text-base font-semibold leading-7 text-black">
                  <div className="absolute left-0 top-0 flex h-10 w-10 items-center justify-center rounded-lg bg-black">
                    <feature.icon
                      className="h-6 w-6 text-white"
                      aria-hidden="true"
                    />
                  </div>
                  {feature.name}
                </dt>
                <dd className="mt-2 text-base leading-7 text-black/60">
                  {feature.description}
                </dd>
              </div>
            ))}
          </dl>
        </div>

        {/* Win-Win Situation Section */}
        <div className="mx-auto mt-24 max-w-5xl text-center sm:mt-32">
          <h2
            className={`flex items-center justify-center gap-x-3 text-4xl font-bold tracking-tight text-black sm:text-5xl ${instrumentSerif.className}`}
          >
            <Target className="h-10 w-10 text-black" />
            The Win-Win Situation
          </h2>
          <p className="mt-6 text-lg leading-8 text-black/60">
            Traditional lotteries take your money and most people lose
            everything. We changed the game entirely.
          </p>
        </div>

        <div className="mx-auto mt-16 grid max-w-md grid-cols-1 gap-8 lg:max-w-4xl lg:grid-cols-2">
          <div className="flex flex-col rounded-2xl bg-slate-50/70 p-8 shadow-lg ring-1 ring-slate-900/5 backdrop-blur-md">
            <h3 className="flex items-center gap-x-2 text-lg font-semibold uppercase leading-7 text-black">
              <Trophy className="h-6 w-6 text-yellow-500" />
              IF YOU WIN
            </h3>
            <ul className="mt-4 flex flex-1 flex-col gap-y-3 text-base leading-7 text-black/80">
              <li className="flex items-start gap-x-3">
                <Check className="h-6 w-6 flex-none text-black" />
                <span>Get the entire prize pool (the yield generated).</span>
              </li>
              <li className="flex items-start gap-x-3">
                <Check className="h-6 w-6 flex-none text-black" />
                <span>Your original LINK deposit is untouched.</span>
              </li>
              <li className="flex items-start gap-x-3">
                <Check className="h-6 w-6 flex-none text-black" />
                <span>A massive, positive-sum return on your ticket.</span>
              </li>
            </ul>
          </div>

          <div className="flex flex-col rounded-2xl bg-slate-50/70 p-8 shadow-lg ring-1 ring-slate-900/5 backdrop-blur-md">
            <h3 className="flex items-center gap-x-2 text-lg font-semibold uppercase leading-7 text-black">
              <Shield className="h-6 w-6 text-blue-500" />
              IF YOU DON'T WIN
            </h3>
            <ul className="mt-4 flex flex-1 flex-col gap-y-3 text-base leading-7 text-black/80">
              <li className="flex items-start gap-x-3">
                <Check className="h-6 w-6 flex-none text-black" />
                <span>Keep your entire staked deposit. You lose nothing.</span>
              </li>
              <li className="flex items-start gap-x-3">
                <Check className="h-6 w-6 flex-none text-black" />
                <span>
                  Automatically get entered into the next lottery round.
                </span>
              </li>
              <li className="flex items-start gap-x-3">
                <Check className="h-6 w-6 flex-none text-black" />
                <span>Play again or withdraw your funds at any time.</span>
              </li>
            </ul>
          </div>
        </div>

        <div className="mt-12 flex justify-center">
          <div className="relative rounded-full bg-black px-6 py-3 text-base leading-6 text-white shadow-lg">
            <PartyPopper className="absolute left-3 top-1/2 h-8 w-8 -translate-y-1/2 text-yellow-400" />
            <span className="ml-8 font-semibold">
              Result: Everyone walks away with something !
            </span>
          </div>
        </div>
      </div>
    </section>
  );
};

export default About;
